[package]
name = "supertris"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec = "0.7.6"
bincode = "2.0.1"
color-eyre = "0.6.5"
dashmap = "6.1.0"
eframe = "0.32.1"
rand = "0.9.2"
rayon = "1.11.0"
rfd = "0.15.4"
tracing = "0.1.41"
tracing-error = "0.2.1"
tracing-subscriber = "0.3.20"
